remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
title: cargo-selector
description: Cargo subcommand to select and execute binary/example targets
show_downloads: false