name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        versions:
          - stable
          - '1.79.0' # MSRV
        os:
          - ubuntu-24.04
          - macos-14
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.versions }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Version
        run: |
          rustc --version
          cargo --version
          cargo fmt -- --version
          cargo clippy -- --version
      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: cargo test --verbose
