Set Shell zsh

Output demo.gif

Set FontSize 15
Set Width 1000
Set Height 500
Set Padding 15
Set WindowBar Colorful
Set BorderRadius 20

Set Theme "iceberg-dark"

Sleep 500ms

Type@100ms "cargo selector"
Sleep 500ms
Enter
Sleep 1s

Ctrl+N
Sleep 500ms
Ctrl+N
Sleep 500ms
Ctrl+N
Sleep 1s

Type@700ms "col"
Sleep 1s
Ctrl+W
Sleep 500ms

Type@700ms "dm"
Sleep 500ms
Ctrl+N
Sleep 500ms
Ctrl+N
Sleep 500ms
Enter

Sleep 3s
